name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-elixir:
    name: Build and test
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    strategy:
      fail-fast: false
      matrix:
        elixir: [1.14.x, 1.13.x, 1.12.x, 1.11.x, 1.10.x, 1.9.x, 1.8.x, 1.7.x]
        include:
          - elixir: 1.7.x
            otp: 20.x
          - elixir: 1.8.x
            otp: 20.x
          - elixir: 1.9.x
            otp: 21.x
          - elixir: 1.10.x
            otp: 22.x
          - elixir: 1.11.x
            otp: 23.x
          - elixir: 1.12.x
            otp: 24.x
          - elixir: 1.13.x
            otp: 25.x
          - elixir: 1.14.x
            otp: 25.x

    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp }}
        elixir-version: ${{ matrix.elixir }}
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}-${{ matrix.otp }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get --force
    - name: Run tests
      run: mix test
