name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-elixir:
    name: Build and test
    runs-on: ubuntu-22.04
    env:
      MIX_ENV: test
      FORCE_COLOR: 1
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              elixir: 1.13.x
              otp: 24.3
          - pair:
              elixir: 1.14.x
              otp: 25.3
          - pair:
              elixir: 1.15.6
              otp: 26.0.2

    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.pair.otp }}
        elixir-version: ${{ matrix.pair.elixir }}
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: mix-${{ runner.os }}-${{ hashFiles('**/mix.lock') }}-${{ matrix.pair.otp }}
        restore-keys: mix-${{ runner.os }}-
    - name: Install dependencies
      run: mix deps.get --only test
    - name: Compile deps
      run: mix deps.compile
    - name: Run tests
      run: mix test
